{
 "title": "EclipseLink Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statement Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(eclipselink_statement_execute_seconds_sum{application=\"$application\", instance=\"$instance\"}[2m]) / irate(eclipselink_statement_execute_seconds_count{application=\"$application\", instance=\"$instance\"}[2m])",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Row Fetch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(eclipselink_row_fetch_seconds_sum{application=\"$application\", instance=\"$instance\"}[2m]) / irate(eclipselink_row_fetch_seconds_count{application=\"$application\", instance=\"$instance\"}[2m])",
     "legendFormat": "row fetch time"
    }
   ]
  },
  {
   "title": "Client Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(eclipselink_clientsession_sessions_total{application=\"$application\", instance=\"$instance\"}[2m])",
     "legendFormat": "{{op}}"
    }
   ]
  },
  { "title": "Shared Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Cache coordination time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(eclipselink_cache_coordination_seconds_sum{application=\"$application\", instance=\"$instance\"}[2m]) / irate(eclipselink_cache_coordination_seconds_count{application=\"$application\", instance=\"$instance\"}[2m])",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Remote Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "irate(eclipselink_remote_messages_total{application=\"$application\", instance=\"$instance\"}[2m])",
     "legendFormat": "{{op}}"
    }
   ]
  }
 ]
}